[project]
name = "commentlint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.62.0",
    "ollama>=0.5.3",
    "openai>=1.99.6",
]

[project.scripts]
commentlint = "commentlint.cli:main"
